hmpps-auth:
  url: "http://localhost:8090/auth"

hmpps:
  sqs:
    enabled: false
    provider: localstack
    queues:
      jdarequestqueus:
        queuename: ${HMPPS_JDA_REQUEST_QUEUE_NAME}
        dlqName: ${HMPPS_JDA_REQUEST_DLQ_NAME}
      jdaresponsequeus:
        queuename: ${HMPPS_JDA_RESPONSE_QUEUE_NAME}
        dlqName: ${HMPPS_JDA_RESPONSE_DLQ_NAME}
  jda:
    worker:
      api:
        base-url: https://justice-data-agent-worker-dev.hmpps.service.justice.gov.uk
  api:
    timeout: 10s

